export const SEARCH_FOCUS = "SEARCH_FOCUS";

export const SEARCH_BLIUR = "SEARCH_BLIUR";

export const CHANGE_LIST = "CHANGE_LIST";

export const MOUSEENTER = "MOUSEENTER";

export const MOUSELEAVE = "MOUSELEAVE";

export const CHANGEPAGE = "CHANGEPAGE";

export const CHANGELIST = "CHANGELIST";

export const CHANGELIST1 = "CHANGELIST1";

export const GETMORELIST = "GETMORELIST";

export const SCROLLTOPSHOW = "SCROLLTOPSHOW";

export const GETDETAILLIST = "GETDETAILLIST";

export const LOGINFOCUSED = "LOGINFOCUSED";

export const BINDLELOGIN = "BINDLELOGIN";

export const BINDLELOGINFOCUSED = "BINDLELOGINFOCUSED";

export const OUTFOCUSED = "OUTFOCUSED";

export const BINDLEREGISTERFOCUSED = "BINDLEREGISTERFOCUSED";
